### ISSUE TITLE
Add RadentscheidWordpressLocations to the list

### ISSUE THREAD

**Issue by steampixel** [mltbnz/awesome-bikeprojects#36]
Would that be a candidate for the list? https://github.com/steampixel/RadentscheidWordpressLocations

**Comment by mltbnz** [comment]
Yes sure. You want to create a PR for it?

**Comment by steampixel** [comment]
This was my first idea :-) But can you give me some hint on where this project should appear in the list?

**Comment by mltbnz** [comment]
Good question. The list is lacking a structure but that is on my to do list.
So I’d say put it wherever you think it is best and I will work it in to structure in the next weeks. Under what section header would you put it if you could choose one?

**Comment by steampixel** [comment]
Puh! That is not easy to answer. This software touches many topics such as "civic tech, data literacy, security, ...". I don't know how. But there is maybe a way to tag the projects with several keys instead of pushing them into static categories. But I have no idea on how to do this with a simple markdown document. I think it would be easier to sort the projects by a main category. For this project I would prefer "civic tech".

**Comment by mltbnz** [comment]
I like the idea of adding tags or badges. 
Civic tech sounds like a good section name

**Comment by mltbnz** [comment]
#38
