### ISSUE TITLE
Add RadlVorrangNetz by MunichWays

### ISSUE THREAD

**Issue by thomas-munichways** [mltbnz/awesome-bikeprojects#37]
[MunichWays ](https://www.munichways.com/) visualization and analyzes of all major roads in Munich according to the traffic light principle. ([code](https://github.com/AppWerft/MunichWays)), ([map](https://usocialmaps.carto.com/builder/dfd7b295-73a7-4dfe-85e6-933dd7fe5787/embed))

**Comment by mltbnz** [comment]
PR is welcome 😄
