### ISSUE TITLE
add https://tally.wikinaut.de/

### ISSUE THREAD

**Issue by Wikinaut** [mltbnz/awesome-bikeprojects#54]
Einfaches, konfigurierbares Tool für Verkehrszählungen, das im Browser läuft.
![grafik](https://user-images.githubusercontent.com/1151915/120864445-8311b080-c58c-11eb-8cc6-b000ba4499a7.png)

**Comment by ZerdoX-x** [comment]
Uhm.. What is this and why?

**Comment by Wikinaut** [comment]
> Uhm.. What is this and why?

"tally", engl. counter, list


The tool works in the browser (Desktop, Smartphone…) and you can count items (fpr example, when you count traffic this would be bicycles, cars, busses for example). The list and names of items can be easily configured and is save in the browser's local storage (no data on the server).

**Comment by ZerdoX-x** [comment]
Why just not using regular text notes app?...
I don't think this will be added to README

**Comment by Wikinaut** [comment]
added to the fork https://github.com/Wikinaut/awesome-bikeprojects

**Comment by Wikinaut** [comment]
Source code is https://github.com/Wikinaut/tally

**Comment by ZerdoX-x** [comment]
Bruh
