### ISSUE TITLE
add pyxelate – open source GUI script to partially pixelate images or short video clips.

### ISSUE THREAD

**Issue by Wikinaut** [mltbnz/awesome-bikeprojects#57]
https://github.com/blackstream-x/pyxelate is an open source GUI script written in Python to partially pixelate images or short video clips. Uses ffmpeg.

**Comment by gorgobacka** [comment]
@Wikinaut: How is this project related to bikes?

**Comment by Wikinaut** [comment]
> @Wikinaut: How is this project related to bikes?

For documenting situations and aggressive car drivers like this:
https://twitter.com/Wikinaut/status/1443866702866010152?s=20

**Comment by Wikinaut** [comment]
add to the fork https://github.com/Wikinaut/awesome-bikeprojects
